# Generated by Django 4.2.5 on 2023-09-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptarea', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='pub_date',
        ),
    ]
